"""Multi-Device Orchestration & Satellite Topology Contracts.

Defines schemas and enums for asymmetric cryptographic device identity,
mTLS pairing lifecycle, device capabilities, presence and heartbeat tracking,
wake-event arbitration, cross-device context handoff, and task migration.
"""

from datetime import UTC, datetime
from enum import StrEnum
from typing import Any
from uuid import uuid4

from pydantic import BaseModel, Field


def _gen_id() -> str:
    return uuid4().hex


def _utc_now() -> datetime:
    return datetime.now(UTC)


class DeviceRole(StrEnum):
    """Architectural role of a device within the PIXEL topology."""
    PRIMARY_PC = "PRIMARY_PC"
    MOBILE_NODE = "MOBILE_NODE"
    SATELLITE_MIC_SPEAKER = "SATELLITE_MIC_SPEAKER"
    SATELLITE_DISPLAY = "SATELLITE_DISPLAY"
    HEADLESS_SENSOR = "HEADLESS_SENSOR"
    EDGE_COMPUTE = "EDGE_COMPUTE"


class DeviceCapability(StrEnum):
    """Typed capabilities supported by a device."""
    MICROPHONE = "MICROPHONE"
    SPEAKER = "SPEAKER"
    DISPLAY = "DISPLAY"
    CAMERA = "CAMERA"
    WAKE_WORD = "WAKE_WORD"
    VOICE_INPUT = "VOICE_INPUT"
    VOICE_OUTPUT = "VOICE_OUTPUT"
    DESKTOP_CONTROL = "DESKTOP_CONTROL"
    ANDROID_CONTROL = "ANDROID_CONTROL"
    CODE_EXECUTION = "CODE_EXECUTION"
    LOCAL_LLM = "LOCAL_LLM"
    REMOTE_LLM = "REMOTE_LLM"
    BATTERY = "BATTERY"
    NETWORK = "NETWORK"


class DeviceTrustState(StrEnum):
    """Cryptographic trust and authorization state."""
    UNPAIRED = "UNPAIRED"
    PAIRING_CHALLENGE = "PAIRING_CHALLENGE"
    PAIRED = "PAIRED"
    TRUSTED = "TRUSTED"
    REVOKED = "REVOKED"
    BLOCKED = "BLOCKED"


class DevicePresenceState(StrEnum):
    """Real-time network presence state."""
    ONLINE = "ONLINE"
    CONNECTING = "CONNECTING"
    DEGRADED = "DEGRADED"
    OFFLINE = "OFFLINE"
    UNAVAILABLE = "UNAVAILABLE"


class DeviceHealthState(StrEnum):
    """Operational health status independent of presence."""
    HEALTHY = "HEALTHY"
    DEGRADED = "DEGRADED"
    UNAVAILABLE = "UNAVAILABLE"
    UNKNOWN = "UNKNOWN"


class DeviceIdentity(BaseModel):
    """Canonical cryptographic identity and profile of a PIXEL device."""
    device_id: str = Field(..., description="Unique stable hardware/node ID")
    device_type: DeviceRole = Field(..., description="Device role in topology")
    device_name: str = Field(..., description="Human-readable node label")
    public_key_fingerprint: str = Field(..., description="SHA-256 fingerprint of public key/cert")
    certificate_pem: str | None = Field(default=None, description="Provisioned mTLS X.509 certificate PEM")
    capabilities: list[DeviceCapability] = Field(default_factory=list, description="Supported hardware capabilities")
    protocol_version: str = Field(default="1.0.0", description="Orchestration protocol version")
    software_version: str = Field(default="1.0.0", description="Installed PIXEL node version")
    trust_state: DeviceTrustState = Field(default=DeviceTrustState.UNPAIRED, description="Current trust lifecycle state")
    created_at: datetime = Field(default_factory=_utc_now)
    updated_at: datetime = Field(default_factory=_utc_now)


class DevicePresenceRecord(BaseModel):
    """Volatile presence and telemetry state for an active device."""
    device_id: str = Field(..., description="Device ID matching DeviceIdentity")
    presence_state: DevicePresenceState = Field(default=DevicePresenceState.OFFLINE)
    health_state: DeviceHealthState = Field(default=DeviceHealthState.UNKNOWN)
    last_heartbeat: datetime = Field(default_factory=_utc_now)
    ip_address: str | None = Field(default=None)
    rtt_ms: float = Field(default=0.0, ge=0.0)
    active_session_id: str | None = Field(default=None)
    battery_level: int | None = Field(default=None, ge=0, le=100)
    is_charging: bool = Field(default=False)
    metadata: dict[str, Any] = Field(default_factory=dict)


class PairingRequest(BaseModel):
    """Initiate pairing request sent by an unpaired device."""
    device_id: str = Field(..., description="Requesting device identifier")
    device_name: str = Field(..., description="Display name of device")
    device_role: DeviceRole = Field(..., description="Role requested")
    capabilities: list[DeviceCapability] = Field(default_factory=list)
    public_key_pem: str = Field(..., description="Public key or CSR in PEM format")
    nonce: str = Field(default_factory=_gen_id, description="Anti-replay challenge nonce")
    timestamp: datetime = Field(default_factory=_utc_now)


class PairingChallenge(BaseModel):
    """Ephemeral challenge generated by Core requiring user authorization."""
    challenge_id: str = Field(default_factory=_gen_id)
    device_id: str = Field(..., description="Target device for challenge")
    pin_code: str = Field(..., description="Short alphanumeric or numeric pairing code")
    nonce: str = Field(..., description="Cryptographic salt/nonce")
    expires_at: datetime = Field(..., description="Challenge expiration cutoff")
    attempts_remaining: int = Field(default=3, ge=0)


class PairingConfirmation(BaseModel):
    """User or device authorization response to complete pairing."""
    challenge_id: str = Field(...)
    device_id: str = Field(...)
    pin_code: str = Field(...)
    user_confirmed: bool = Field(default=True)
    auth_signature: str = Field(default="", description="Optional HMAC or signature token")


class PairingResponse(BaseModel):
    """Outcome of pairing attempt containing signed certificate or rejection."""
    success: bool = Field(...)
    device_id: str = Field(...)
    certificate_pem: str | None = Field(default=None, description="Signed device mTLS certificate")
    root_ca_pem: str | None = Field(default=None, description="PIXEL Trust Root CA certificate")
    trust_state: DeviceTrustState = Field(default=DeviceTrustState.UNPAIRED)
    error_message: str | None = Field(default=None)
    server_time: datetime = Field(default_factory=_utc_now)


class WakeArbitrationCandidate(BaseModel):
    """Candidate detection frame sent by a satellite/device hearing the wake word."""
    candidate_id: str = Field(default_factory=_gen_id)
    device_id: str = Field(..., description="Reporting node ID")
    wake_event_id: str = Field(..., description="Correlated utterance / wake event group ID")
    timestamp_ms: int = Field(..., description="Detection timestamp in milliseconds")
    confidence: float = Field(default=0.0, ge=0.0, le=1.0, description="Wake-word model confidence score")
    snr_db: float = Field(default=0.0, description="Signal-to-noise ratio in dB")
    estimated_distance_m: float | None = Field(default=None, ge=0.0, description="Estimated distance from speaker in meters")
    is_current_interaction_owner: bool = Field(default=False, description="True if node is already the active audio owner")
    rtt_ms: float = Field(default=0.0, ge=0.0, description="Network round-trip latency to Core")


class WakeArbitrationResult(BaseModel):
    """Outcome of central wake arbitration indicating the single active winner."""
    arbitration_id: str = Field(default_factory=_gen_id)
    wake_event_id: str = Field(..., description="Correlated wake event ID")
    winner_device_id: str = Field(..., description="Elected active audio owner node")
    winner_score: float = Field(..., description="Winning arbitration score")
    suppressed_device_ids: list[str] = Field(default_factory=list, description="Nodes that must discard their audio capture")
    candidates_evaluated: int = Field(default=1, ge=1)
    timestamp: datetime = Field(default_factory=_utc_now)


class ContextHandoffPayload(BaseModel):
    """Scoped conversation and session context transferred between nodes."""
    handoff_id: str = Field(default_factory=_gen_id)
    source_device_id: str = Field(...)
    target_device_id: str = Field(...)
    session_id: str = Field(...)
    conversation_context: dict[str, Any] = Field(default_factory=dict, description="Scoped dialog state; credentials stripped")
    active_language: str = Field(default="en")
    timestamp: datetime = Field(default_factory=_utc_now)


class TaskHandoffPayload(BaseModel):
    """Canonical task state migration payload with optimistic concurrency lease."""
    handoff_id: str = Field(default_factory=_gen_id)
    task_id: str = Field(...)
    source_device_id: str = Field(...)
    target_device_id: str = Field(...)
    task_version: int = Field(..., ge=1, description="Monotonically increasing task checkpoint version")
    concurrency_lease_token: str = Field(..., description="Active cryptographic lease token for single execution")
    plan_steps: list[dict[str, Any]] = Field(default_factory=list)
    current_step_index: int = Field(default=0, ge=0)
    pending_approval: dict[str, Any] | None = Field(default=None, description="L6 security card if action awaits confirmation")
    state_snapshot: dict[str, Any] = Field(default_factory=dict)
    timestamp: datetime = Field(default_factory=_utc_now)
